# Generated by Django 4.0.6 on 2023-01-19 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_category_subscribes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='subscribes',
            new_name='subscribers',
        ),
    ]
