# Generated by Django 3.2.7 on 2021-09-29 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0002_alter_author_ratingauthor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='ratingAuthor',
            field=models.SmallIntegerField(default=0.0),
        ),
    ]
